import Head from "next/head";
import Footer from "../components/Footer";
import Form from "../components/Form";
import Header from "../components/Header";
import Main from "../components/Main";

export default function Home() {
  return (
    <>
      <Head>
        <title>Iguane Déménagement | Accueil</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Main />
      <Form />
    </>
  );
}
