import React from "react";
import Head from "next/head";
import Nav from "../components/Nav";
import ProductShop from "../components/shop/ProductShop";
import Form from "../components/Form";

const shop = () => {
  return (
    <>
      <Head>
        <title>Iguane Déménagement | Shop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <ProductShop />
      <Form />
    </>
  );
};

export default shop;
